version: "3.9"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres-order:
    image: postgres:13
    environment:
      POSTGRES_DB: trendylike_order_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: peninsula03
    ports:
      - 5432:5432

  postgres-inventory:
    image: postgres:13
    environment:
      POSTGRES_DB: trendylike_inventory_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: peninsula03
    ports:
      - 5433:5432

  postgres-payment:
    image: postgres:13
    environment:
      POSTGRES_DB: trendylike_payment_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: peninsula03
    ports:
      - 5434:5432

  order-service:
    build: ./order-service
    depends_on:
      - postgres-order
      - kafka
    environment:
      DB_HOST: postgres-order
      DB_PORT: 5432
      DB_NAME: trendylike_order_dev
      DB_USER: postgres
      DB_PASSWORD: peninsula03
      KAFKA_BOOTSTRAP: kafka:9092
    ports:
      - 8080:8080

  inventory-service:
    build: ./inventory-service
    depends_on:
      - postgres-inventory
      - kafka
    environment:
      DB_HOST: postgres-inventory
      DB_PORT: 5432
      DB_NAME: trendylike_inventory_dev
      DB_USER: postgres
      DB_PASSWORD: peninsula03
      KAFKA_BOOTSTRAP: kafka:9092
    ports:
      - 8081:8081

  payment-service:
    build: ./payment-service
    depends_on:
      - postgres-payment
      - kafka
    environment:
      DB_HOST: postgres-payment
      DB_PORT: 5432
      DB_NAME: trendylike_payment_dev
      DB_USER: postgres
      DB_PASSWORD: peninsula03
      KAFKA_BOOTSTRAP: kafka:9092
    ports:
      - 8082:8082
